language: php
sudo: false

php:
    - 7.1

before_install:
    - phpenv config-add travis.php.ini

install:
    - composer update --prefer-stable --prefer-dist

script:
    - composer test

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml
